- hosts: localhost
  tasks: 
  # - name: create ec2 instance
      - ec2:
          aws_access_key: AKIAJXFKBPFEE6WJ5FQA
          aws_secret_key: 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
          image: ami-5b673c34
         # wait: yes
          instance_type: t2.micro
        #  group_id: security_group.group_id
          region: ap-south-1
         # count_tag:
          #  Name: apacheserver
         # exact_count: 1
#       - register: ec2
